name: Security Scans

on:
  workflow_dispatch:

jobs:
  pre-phase:
    name: Pre Phase - Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Pre Phase Security Scan
        uses: clockhash-kiran/scan-actions/hashsecured-scan@main
        with:
          phase: "pre"
          target_url: "gitlab.com/clockhash-kiran/DVWA"
          user_id: "SnQjWROu26YUjZton3t7N9YHzOja3uQA"
          project_id: "JrSpTfrI_0PjG3l1hU3zo"
          api_token: ${{ secrets.API_TOKEN }}
          branch: "master"

  mid-phase:
    name: Mid Phase - Container Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Mid Phase Security Scan
        uses: clockhash-kiran/scan-actions/hashsecured-scan@main
        with:
          phase: "mid"
          target_url: "nginx:latest"
          user_id: "SnQjWROu26YUjZton3t7N9YHzOja3uQA"
          project_id: "JrSpTfrI_0PjG3l1hU3zo"
          api_token: ${{ secrets.API_TOKEN }}

  post-phase:
    name: Post Phase - Deployment Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Post Phase Security Scan
        uses: clockhash-kiran/scan-actions/hashsecured-scan@main
        with:
          phase: "post"
          target_url: "https://example.com"
          user_id: "SnQjWROu26YUjZton3t7N9YHzOja3uQA"
          project_id: "JrSpTfrI_0PjG3l1hU3zo"
          api_token: ${{ secrets.API_TOKEN }}
