name: CI/CD with Scans

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-phase:
    name: Pre Phase - Gitleaks + Semgrep (already triggered via push webhook)
    runs-on: ubuntu-latest
    steps:
      - name: Note
        run: echo "Pre-phase handled via GitHub push webhook"

  mid-phase:
    name: Mid Phase - Trigger Trivy Scan
    needs: pre-phase
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Trivy Scan
        run: |
          curl -X POST https://7cfb-103-148-20-83.ngrok-free.app/scan/mid-request \
               -H "Content-Type: application/json" \
               -d '{
                     "target_url": "https://github.com/clockhash-kiran/DVWA",
                     "user_id": "1ee6f687-f458-450f-933f-263255cf866d",
                     "project_id": "3b908245-fa68-4fef-b08d-14722ec8a7c7"
                   }'

  deploy:
    name: Deployment Step
    needs: mid-phase
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Your App
        run: |
          echo "TODO: Deploy your app to staging/prod"

  post-phase:
    name: Post Phase - Trigger ZAP Scan
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ZAP Scan
        run: |
          curl -X POST https://7cfb-103-148-20-83.ngrok-free.app/scan/post-request \
               -H "Content-Type: application/json" \
               -d '{
                     "target_url": "https://example.com",
                     "user_id": "1ee6f687-f458-450f-933f-263255cf866d",
                     "project_id": "3b908245-fa68-4fef-b08d-14722ec8a7c7"
                   }'
