name: Mid Phase Scans

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mid-phase:
    name: Mid Phase - Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Mid Phase Security Scan
        uses: clockhash-kiran/scan-actions/mid-phase@main
        with:
          target_url: "nginx:latest"
          user_id: "1ee6f687-f458-450f-933f-263255cf866d"
          project_id: "3b908245-fa68-4fef-b08d-14722ec8a7c7"
          api_token: ${{ secrets.API_TOKEN }}
