name: Mid Phase Scans

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mid-phase:
    name: Mid Phase - Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Mid Phase Security Scan
        uses: clockhash-kiran/scan-actions/mid-phase@testing
        with:
          target_url: "nginx:latest"
          user_id: "mnKgvDd9StJRpKSZqkW1XKucZOrbOU44"
          project_id: "ZpIkYc4pD9CjFfCR7U29J"
          api_token: ${{ secrets.API_TOKEN }}



