name: CI/CD with Scans

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  mid-phase:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Trivy Scan
        uses: ./.github/actions/trivy-scan
        with:
          api_url: "https://0adb-122-165-243-208.ngrok-free.app/scan/mid-request"
          target_url: "https://github.com/clockhash-kiran/DVWA"
          user_id: "1ee6f687-f458-450f-933f-263255cf866d"
          project_id: "3b908245-fa68-4fef-b08d-14722ec8a7c7"
